version: '2'

services:
  flask:
      build: .
      image: project
      ports:
          - "8001:5000"
      environment:
          FLASK_APP: runner.py
          FLASK_DEBUG: 'True'
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_NAME: ${DB_NAME}
          DB_HOST: ${DB_HOST}
          DB_PORT: ${DB_PORT}
      links:
          - highcharts
      volumes:
          - ./project:/project
#      tty: true

  postgres:
      restart: always
      image: postgres:9.6
      environment:
          POSTGRES_USER: ${DB_USER}
          POSTGRES_PASSWORD: ${DB_PASSWORD}
          POSTGRES_DB: ${DB_NAME}
      ports:
          - "5432:5432"

  rabbitmq:
      image: rabbitmq:3.6.6-management
      restart: "always"
      ports:
          - "5672:5672"
          - "15672:15672"
      environment:
          RABBITMQ_DEFAULT_PASS: mypass
          RABBITMQ_DEFAULT_USER: myuser
          RABBITMQ_DEFAULT_VHOST: myvhost

  celery:
      image: project
      container_name: worker_celery
      command: celery -A app.celery worker
      environment:
          FLASK_APP: runner.py
          FLASK_DEBUG: 'True'
          DB_USER: ${DB_USER}
          DB_PASSWORD: ${DB_PASSWORD}
          DB_NAME: ${DB_NAME}
          DB_HOST: ${DB_HOST}
          DB_PORT: ${DB_PORT}
      links:
          - rabbitmq
          - redis
          - highcharts
      depends_on:
          - flask

  redis:
      image: redis
      container_name: redis
      ports:
          - "6379:6379"

      restart: always

  highcharts:
      image: onsdigital/highcharts-export-node
      container_name: highcharts
      ports:
          - "8889:8080"
